### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by Semolce** [alexanderbergman7/GNARF#1]
Hi alexander, thank you for your awesome work! I really want to implement your method in my own work. Is it convenient for you to give me an approximate releasing date? I will really appreciate it.

**Comment by alexanderbergman7** [comment]
Hi Semolce, thank you for your interest! I have uploaded the majority of the code and modules used for the human body training. Most of these are shared for human face and single-scene overfitting, but I have yet to clean them all together and write a quick-start usage guide. However, you can use the modules in your own work as you please. Feel free to reach out with any issues you have getting things working :)
